{"message":"failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]\n    at Pool.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\topologies\\server.js:438:11)\n    at Pool.emit (events.js:223:5)\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:561:14\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:994:11\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:31:7\n    at callback (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:264:5)\n    at Socket.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:294:7)\n    at Object.onceWrapper (events.js:313:26)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)","name":"MongoNetworkError","level":"error","timestamp":"2020-03-26T09:50:41.948Z"}
{"message":"failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]\n    at Pool.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\topologies\\server.js:438:11)\n    at Pool.emit (events.js:223:5)\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:561:14\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:994:11\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:31:7\n    at callback (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:264:5)\n    at Socket.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:294:7)\n    at Object.onceWrapper (events.js:313:26)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)","name":"MongoNetworkError","level":"error","timestamp":"2020-03-26T09:50:55.444Z"}
{"message":"failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]\n    at Pool.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\topologies\\server.js:438:11)\n    at Pool.emit (events.js:223:5)\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:561:14\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:994:11\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:31:7\n    at callback (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:264:5)\n    at Socket.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:294:7)\n    at Object.onceWrapper (events.js:313:26)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)","name":"MongoNetworkError","level":"error","timestamp":"2020-03-26T09:52:18.915Z"}
{"message":"failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]\n    at Pool.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\topologies\\server.js:438:11)\n    at Pool.emit (events.js:223:5)\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:561:14\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:994:11\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:31:7\n    at callback (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:264:5)\n    at Socket.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:294:7)\n    at Object.onceWrapper (events.js:313:26)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)","name":"MongoNetworkError","level":"error","timestamp":"2020-03-26T09:52:59.031Z"}
{"message":"failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]\n    at Pool.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\topologies\\server.js:438:11)\n    at Pool.emit (events.js:223:5)\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:561:14\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:994:11\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:31:7\n    at callback (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:264:5)\n    at Socket.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:294:7)\n    at Object.onceWrapper (events.js:313:26)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)","name":"MongoNetworkError","level":"error","timestamp":"2020-03-26T09:53:06.845Z"}
{"message":"failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]\n    at Pool.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\topologies\\server.js:438:11)\n    at Pool.emit (events.js:223:5)\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:561:14\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:994:11\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:31:7\n    at callback (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:264:5)\n    at Socket.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:294:7)\n    at Object.onceWrapper (events.js:313:26)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)","name":"MongoNetworkError","level":"error","timestamp":"2020-03-26T09:53:34.908Z"}
{"message":"failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]\n    at Pool.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\topologies\\server.js:438:11)\n    at Pool.emit (events.js:223:5)\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:561:14\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:994:11\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:31:7\n    at callback (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:264:5)\n    at Socket.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:294:7)\n    at Object.onceWrapper (events.js:313:26)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)","name":"MongoNetworkError","level":"error","timestamp":"2020-03-26T09:54:07.998Z"}
{"message":"failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]\n    at Pool.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\topologies\\server.js:438:11)\n    at Pool.emit (events.js:223:5)\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:561:14\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:994:11\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:31:7\n    at callback (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:264:5)\n    at Socket.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:294:7)\n    at Object.onceWrapper (events.js:313:26)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)","name":"MongoNetworkError","level":"error","timestamp":"2020-03-26T09:56:09.231Z"}
{"message":"failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]\n    at Pool.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\topologies\\server.js:438:11)\n    at Pool.emit (events.js:223:5)\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:561:14\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:994:11\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:31:7\n    at callback (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:264:5)\n    at Socket.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:294:7)\n    at Object.onceWrapper (events.js:313:26)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)","name":"MongoNetworkError","level":"error","timestamp":"2020-03-26T09:58:41.146Z"}
{"message":"failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]\n    at Pool.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\topologies\\server.js:438:11)\n    at Pool.emit (events.js:223:5)\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:561:14\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:994:11\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:31:7\n    at callback (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:264:5)\n    at Socket.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:294:7)\n    at Object.onceWrapper (events.js:313:26)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)","name":"MongoNetworkError","level":"error","timestamp":"2020-03-26T09:58:49.316Z"}
{"message":"failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]\n    at Pool.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\topologies\\server.js:438:11)\n    at Pool.emit (events.js:223:5)\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:561:14\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:994:11\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:31:7\n    at callback (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:264:5)\n    at Socket.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:294:7)\n    at Object.onceWrapper (events.js:313:26)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)","name":"MongoNetworkError","level":"error","timestamp":"2020-03-26T10:14:16.396Z"}
{"message":"failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]\n    at Pool.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\topologies\\server.js:438:11)\n    at Pool.emit (events.js:223:5)\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:561:14\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:994:11\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:31:7\n    at callback (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:264:5)\n    at Socket.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:294:7)\n    at Object.onceWrapper (events.js:313:26)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)","name":"MongoNetworkError","level":"error","timestamp":"2020-03-26T10:16:19.549Z"}
{"message":"failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]\n    at Pool.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\topologies\\server.js:438:11)\n    at Pool.emit (events.js:223:5)\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:561:14\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:994:11\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:31:7\n    at callback (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:264:5)\n    at Socket.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:294:7)\n    at Object.onceWrapper (events.js:313:26)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)","name":"MongoNetworkError","level":"error","timestamp":"2020-03-27T13:33:38.404Z"}
{"message":"unsupported charset \"UTF-8\"","stack":"UnsupportedMediaTypeError: unsupported charset \"UTF-8\"\n    at D:\\Practice\\Node\\vidly\\node_modules\\body-parser\\lib\\read.js:83:18\n    at invokeCallback (D:\\Practice\\Node\\vidly\\node_modules\\raw-body\\index.js:224:16)\n    at processTicksAndRejections (internal/process/task_queues.js:76:11)","name":"UnsupportedMediaTypeError","charset":"utf-8","type":"charset.unsupported","level":"error","timestamp":"2020-03-29T15:24:16.782Z"}
{"message":"unsupported charset \"UTF-8\"","stack":"UnsupportedMediaTypeError: unsupported charset \"UTF-8\"\n    at D:\\Practice\\Node\\vidly\\node_modules\\body-parser\\lib\\read.js:83:18\n    at invokeCallback (D:\\Practice\\Node\\vidly\\node_modules\\raw-body\\index.js:224:16)\n    at processTicksAndRejections (internal/process/task_queues.js:76:11)","name":"UnsupportedMediaTypeError","charset":"utf-8","type":"charset.unsupported","level":"error","timestamp":"2020-03-29T15:25:29.327Z"}
{"message":"failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]\n    at Pool.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\topologies\\server.js:438:11)\n    at Pool.emit (events.js:223:5)\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:561:14\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:994:11\n    at D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:31:7\n    at callback (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:264:5)\n    at Socket.<anonymous> (D:\\Practice\\Node\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:294:7)\n    at Object.onceWrapper (events.js:313:26)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)","name":"MongoNetworkError","level":"error","timestamp":"2020-03-30T13:29:43.002Z"}
